service: prueba-finaktiva

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  architecture: arm64
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15
  environment:
    URI_MONGO: ${env:URI_MONGO}

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
      allowCredentials: false

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
